export const FIELDS  = {
newCasesByPublishDate: 'New cases by publish date',
cumCasesByPublishDate: 'Cumulative cases by publish date',
cumCasesBySpecimenDateRate: 'Rate of cumulative cases by publish date per 100k resident population',
newCasesBySpecimenDate: 'New cases by specimen date',
cumCasesBySpecimenDate: 'Cumulative cases by specimen date',
maleCases: 'Male cases (by age)',
femaleCases: 'Female cases (by age)',

newPillarOneTestsByPublishDate: 'New pillar one tests by publish date',
cumPillarOneTestsByPublishDate: 'Cumulative pillar one tests by publish date',
newPillarTwoTestsByPublishDate: 'New pillar two tests by publish date',
cumPillarTwoTestsByPublishDate: 'Cumulative pillar two tests by publish date',
newPillarThreeTestsByPublishDate: 'New pillar three tests by publish date',
cumPillarThreeTestsByPublishDate: 'Cumulative pillar three tests by publish date',
newPillarFourTestsByPublishDate: 'New pillar four tests by publish date',
cumPillarFourTestsByPublishDate: 'Cumulative pillar four tests by publish date',
newAdmissions: 'New admissions',
cumAdmissions: 'Cumulative number of admissions',
cumAdmissionsByAge: 'Cumulative admissions by age',
cumTestsByPublishDate: 'Cumulative tests by publish date',
newTestsByPublishDate: 'New tests by publish date',
covidOccupiedMVBeds: 'COVID-19 occupied beds with mechanical ventilators',
hospitalCases: 'Hospital cases',
plannedCapacityByPublishDate: 'Planned capacity by publish date',
newDeaths28DaysByPublishDate: 'Deaths within 28 days of positive test',
cumDeaths28DaysByPublishDate: 'Cumulative deaths within 28 days of positive test',
cumDeaths28DaysByPublishDateRate: 'Rate of cumulative deaths within 28 days of positive test per 100k resident population',
newDeaths28DaysByDeathDate: 'Deaths within 28 days of positive test by death date',
cumDeaths28DaysByDeathDate: 'Cumulative deaths within 28 days of positive test by death date',
cumDeaths28DaysByDeathDateRate: 'Rate of cumulative deaths by death date per 100k resident population',
}